### ISSUE TITLE
Suggestion: Embedding into more languages + standalone syntax

### ISSUE THREAD

**Issue by ROpdebee** [Sublime-Instincts/BetterJinja#7]
Not a bug! A feature suggestion :)

Currently, BetterJinja only embeds the Jinja into HTML. I find that a bit of a limitation, since I use Jinja primarily for non-HTML things. It would therefore be cool if BetterJinja shipped with more embedding languages (JSON comes to mind, shell perhaps).

Additionally, regardless of whether more embedding languages are added, I think it'd be beneficial to split up syntax into a base Jinja syntax that can be used on any file, and depend on this base syntax in the embedding ones. For HTML, this would pretty much look like the following:
```yaml
- match: ""
      push: "Packages/HTML/HTML.sublime-syntax"
      with_prototype:
        - include: path/to/base.sublime-syntax#statement_blocks
        - ...
```
This is not too different from how it is already, but now it always loads the HTML by default. Any new embedding language could use the same template, this could probably be automated.

Benefits:
- The standalone syntax can be used on any file, not just HTML files. Of course, the HTML Jinja syntax can already be used on any file, but I can imagine there might be some parsing issues if Sublime tries to parse something that isn't HTML as HTML.
- The standalone file could be used by clients to create their own Jinja2-embedding syntax for the parser of their choice.
- More syntaxes = more features, and this can probably be automated.

Problems:
- How will all those different syntax definitions be distributed? Not everyone will want every language, and if there's 10s of syntax definitions, each for a different variant, it'll become confusing. On the other hand, distributing a mini-package for each is infeasible as well.

Would like to hear your thoughts on this. I'll probably soon experiment with this a bit. I'll also see whether I can use this syntax to create an improved Ansible syntax definition, since Ansible uses Jinja2 extensively in its YAML, but the expressions do not always have to be delimited by braces (certain strings are always parsed as Jinja2 templates). I've written a prototype syntax for Ansible recently, however, that uses my own Jinja2 syntax, so I'll see if I can migrate it.

**Comment by UltraInstinct05** [comment]
As you can probably tell, I have only ever used `Jinja2` with HTML (for Flask & Django, though Django I believe, doesn't use `Jinja2`, but a extremely similar templating language, the name escapes me). 

IMHO, I believe it would be better to ship other variants of `Jinja2` embedded languages with `BetterJinja` as well (rather than have 10's of packages that ship different variant(s)) so that users can just use any variant they like.

As for the syntax break up, that will need some thinking over (The base syntax idea of yours is also one that immediately comes to mind).

I am, of course, always happy to accept PR's to add other variants (I will also experiment with other embedded languages in spare time).

**Comment by UltraInstinct05** [comment]
From a high level overview of Ansible docs, it looks like `Jinja2` embedded in YAML. I guess you should probably be able to use most (if not all) of the existing syntax with a base scope like `source.yaml.jinja`. Just an opinion. This is the first time I am looking at what Ansible is so I may need to play with it before seeing how much the existing syntax is valid for it.

**Comment by ROpdebee** [comment]
> From a high level overview of Ansible docs, it looks like `Jinja2` embedded in YAML. I guess you should probably be able to use most (if not all) of the existing syntax with a base scope like `source.yaml.jinja`. Just an opinion. This is the first time I am looking at what Ansible is so I may need to play with it before seeing how much the existing syntax is valid for it.

For the most part, that is true. However, there's some cases where the Jinja2 expression delimiters are unnecessary (and even discouraged). For example:
```yaml
- name: (Tunnelblick) Ensure auth group usernames are added to keychain.
  command: >
    security add-generic-password -U
    -a username
    -s {{ tblk_auth_group_prefix }}{{ item.name }}
    -w {{ item.username }}
  when: >
    (tblk_auth_usernames_defined.results
    | selectattr('item', 'equalto', item.name)
    | selectattr('rc', 'equalto', 0) | list
    or [{'stdout': ''}])
    | map(attribute='stdout') | first != item.username
  changed_when: yes
  register: added_usernames
  notify: restart tunnelblick
  loop: "{{ tblk_auth_groups_credentials }}"
  loop_control:
    label: "{{ item.name }}"
```

There's some Jinja2 expressions here (in `command:`, `loop:`, and `label:`). However, the `when:` key also uses Jinja2 expressions to evaluate a conditional, and the value given to that key is always interpreted as a Jinja2 expression, so the `{{` and `}}` delimiters are unnecessary (and will raise a warning at runtime). Looking over the current syntax, I don't think those can easily be parsed, even with the necessary prototypes set for the YAML syntax to recognise these special keys, since the expression context requires these delimiters to be present. That's an problem that can easily be fixed though, I think.

I'll also be experimenting some more today, and update you with my findings.
